//Global errors actions
export const SET_ERRORS = "SET_ERRORS";
//Auth actions
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REGISTER = "REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGOUT = "LOGOUT";
//Student actions
export const FETCH_STUDENT = "FETCH_STUDENT";
export const RESET_STUDENT = "RESET_STUDENT";
export const FETCH_STUDENT_START = "FETCH_STUDENT_START";
export const FETCH_STUDENT_END = "FETCH_STUDENT_END";
export const CREATE_STUDENT = "CREATE_STUDENT";
export const CREATE_STUDENT_START = "CREATE_STUDENT_START";
export const CREATE_STUDENT_END = "CREATE_STUDENT_END";
export const UPDATE_STUDENT = "UPDATE_STUDENT";
export const UPDATE_STUDENT_START = "UPDATE_STUDENT_START";
export const UPDATE_STUDENT_END = "UPDATE_STUDENT_END";
export const DELETE_STUDENT = "DELETE_STUDENT";
export const DELETE_STUDENT_START = "DELETE_STUDENT_START";
export const DELETE_STUDENT_END = "DELETE_STUDENT_END";
export const FETCH_STUDENTS_RESULTS = "FETCH_STUDENTS_RESULTS";
export const FETCH_STUDENTS_RESULTS_START = "FETCH_STUDENTS_RESULTS_START";
export const FETCH_STUDENTS_RESULTS_END = "FETCH_STUDENTS_RESULTS_END";
export const FETCH_STUDENTS_QUICK_RESULTS = "FETCH_STUDENTS_QUICK_RESULTS";
export const RESET_RESULTS = "RESET_RESULTS";
export const RESET_QUICK_RESULTS = "RESET_QUICK_RESULTS";
//Alert actions
export const SET_SUCCESS_ALERT = "SET_SUCCESS_ALERT";
export const SET_ERROR_ALERT = "SET_ERROR_ALERT";
export const RESET_ALERT = "RESET_ALERT";
